### ISSUE TITLE
Linting on the fly

### ISSUE THREAD

**Issue by ypt** [DanPurdy/linter-sass-lint#17]
Currently, linting with linter-sass-lint seems to only happen upon saving a file (regardless of the "Lint As You Type" setting on [Linter](https://atom.io/packages/linter). Would it be possible to enable linting on the fly for linter-sass-lint?

https://github.com/DanPurdy/linter-sass-lint/blob/master/lib/main.coffee#L34

The linter-scss-lint plugin seems to have linting on the fly enabled:

https://github.com/AtomLinter/linter-scss-lint/blob/master/lib/init.coffee#L37

**Comment by natorojr** [comment]
+1 Yes! Please.

**Comment by DanPurdy** [comment]
Hi @ypt thanks for this. 

So when I first built this plugin I had a play around with it and found linting on the fly to be a little strange in its behaviour mainly due to how we are parsing the files in sass-lint. We've made a lot of updates to sass-lint recently though so I will definitely look at adding this functionality again, it works a little differently to how this is currently setup but won't take too much to add. Would you prefer to have it behind an option flag? I.e. enable or disable (lint on save) it?

**Comment by ypt** [comment]
Thanks for looking into this @DanPurdy. Re: option flag, whatever's easier for you and/or better for the other users of linter-sass-lint out there. Personally, I think it'd be nice if there was an options flag, but if not, it's not a super big deal. Thanks again!

**Comment by natorojr** [comment]
Thanks for addressing this, @DanPurdy! 

I work with @ypt. I think we would like it to work similar to how [linter-eslint](https://github.com/AtomLinter/linter-eslint) works, which I believe is enabled by default if linter's "Lint As You Type" flag is on.

**Comment by natorojr** [comment]
But I also agree with @ypt ... whatever is the path of least resistance and fastest to rollout.
Thanks

**Comment by DanPurdy** [comment]
The only issue I see currently is the fact that the parser we use throws a lot of errors for incorrect Sass/scss for example leaving the closing bracket off of a block will just report one overall error for the whole file as a parse error until it's added, once that happens other warnings/errors will display as normal until you write something else that can't be parsed.

I'll definitely look into it. Just so you know, 0.5.0 is the next release scheduled with some improved error messages for when sass-lint isn't configured properly 1.0.0 will happen directly after that, large jump in versions just due to the breaking changes I know will have to happen to get this extra functionality in. Got to get sass-lint 1.4.0 out of the door soon too so hopefully it wont be too long before I can give you some sort of update.

Thanks to both of you @ypt, @natorojr for your suggestions.

**Comment by DanPurdy** [comment]
@natorojr @ypt it's been ages but if you're still interested I just pushed 1.0.0 out and it includes lint on fly support. This repository has moved over to the AtomLinter organisation which is where i'll be developing this from now on. 

https://github.com/AtomLinter/linter-sass-lint

**Comment by natorojr** [comment]
thank @DanPurdy !
